/**
 * Component for controlling output that's generated by a consumer of the
 * Regal Game Library and returned to the player.
 *
 * Copyright (c) 2018 Joseph R Cowman
 * Licensed under MIT License (see https://github.com/regal/regal)
 */

export { recycleInstanceOutput } from "./func/recycle-instance-output";
export { buildInstanceOutput } from "./impl";
export { InstanceOutput } from "./instance-output";
export { OutputLine, OutputLineType } from "./output-line";
