/*
 * Contains interfaces for response objects from the Game API.
 *
 * Copyright (c) Joseph R Cowman
 * Licensed under MIT License (see https://github.com/regal/regal)
 */

import { GameMetadata } from "../config";
import { RegalError } from "../error";
import { OutputLine } from "../output";
import { GameInstance } from "../state";

/**
 * Response object of every `GameApi` method, which
 * contains some output and a `GameInstance` if applicable.
 */
export interface GameResponse {
    /**
     * The new instance state of the game.
     *
     * Will not be defined if an error occurred during the request
     * or if `getMetdataCommand` was called.
     */
    instance?: GameInstance;

    /**
     * The output generated by the request, which will vary in
     * structure depending on the request and if it was successful.
     */
    output: GameResponseOutput;
}

/**
 * The output component of a response generated by a request to the `GameApi`.
 */
export interface GameResponseOutput {
    /** Whether the request was executed successfully. */
    wasSuccessful: boolean;

    /** The error that was thrown if `wasSuccessful` is false. */
    error?: RegalError;

    /** Contains any lines of output emitted because of the request. */
    log?: OutputLine[];

    /** Contains the game's metadata if `getMetdataCommand` was called. */
    metadata?: GameMetadata;
}
